# Generated by Django 2.0.4 on 2018-07-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrep', models.CharField(default='votre entreprise', max_length=250, verbose_name='Le nom de votre entreprise')),
                ('nom', models.CharField(default='votre nom', max_length=250, verbose_name='votre nom')),
                ('ville', models.CharField(default='votre ville', max_length=250, verbose_name='Votre ville')),
                ('nbsal', models.PositiveIntegerField(verbose_name='Nombre de salariés')),
                ('pccycliste', models.PositiveIntegerField(choices=[(3, 'Moins de 5 %'), (20, 'Environ un quart'), (55, 'Environ la moitié'), (80, 'Plus de la moitié'), (50, 'Ne sais pas estimer')], default='50', verbose_name='NPourcentages cyclistes')),
                ('dist', models.IntegerField(default=3, verbose_name='Distance Domicile travail moyenne des cyclistes de votre entreprise')),
                ('access', models.CharField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], default='Bonne', max_length=10, verbose_name='Accessibilite du site')),
                ('ctxgeolib', models.FloatField(choices=[(4.9, 'Centre ville ou urbain'), (1.7, 'Périurbain'), (1.5, 'Rural'), (2.2, 'Moyenne nationale')], default='Centre-ville', verbose_name='Contexte geographique')),
                ('g1', models.IntegerField(choices=[(2, 'Réticent'), (25, 'Non sensibilisé'), (45, 'Sensibilisé'), (75, 'Motivé'), (100, 'Impliqué et acteur')], verbose_name='Motivation de la direction de l’entreprise')),
                ('g2', models.IntegerField(choices=[(10, 'Réfractaire aux vélos'), (25, 'Sensibilisé mais pas confiant'), (45, 'Usager ponctuel pour le loisir'), (75, 'Usager quotidien'), (100, 'Cycliste expert')], verbose_name='Motivation des salariés')),
                ('g3', models.IntegerField(choices=[(10, 'Inexistant'), (50, 'En réflexion'), (100, 'Actif')], verbose_name="Etat d'avancement du PDE")),
                ('g4', models.IntegerField(choices=[(10, 'Aucune action envisagée'), (50, 'Actions vélos en réflexion'), (100, 'Actions vélos mises en place')], default=50, verbose_name='Actions vélo')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
