# Generated by Django 2.0.1 on 2018-04-07 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Votre nom')),
                ('entrep', models.CharField(max_length=250, verbose_name='Le nom de votre entreprise')),
                ('adresse', models.CharField(max_length=250, verbose_name='Votre adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Votre ville')),
                ('nbsal', models.IntegerField(default=0, verbose_name='Nombre de salariés')),
                ('partmodal', models.IntegerField(default=0, verbose_name="Nombre de cyclistes dans l'entreprise")),
                ('txpratique', models.IntegerField(default=65, verbose_name='Taux de pratique (en pourcentages de jours travaillés)')),
                ('access', models.TextField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], default='bonne', verbose_name='Accessibilite du site')),
                ('ctxgeolib', models.TextField(choices=[('4.9', 'Centre-ville'), ('1.7', 'Banlieues'), ('1.5', 'Rural'), ('2.2', 'Moyenne nationale')], verbose_name='Contexte geographique')),
                ('g1', models.IntegerField(default=0, verbose_name='Motivation de la direction de l’entreprise')),
                ('g2', models.IntegerField(default=0, verbose_name='Motivation des salariés')),
                ('g3', models.IntegerField(default=0, verbose_name="Etat d'avancement du PDE")),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
