# Generated by Django 2.0.4 on 2018-05-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrep', models.CharField(default='votre entreprise', max_length=250, verbose_name='Le nom de votre entreprise')),
                ('nom', models.CharField(default='votre nom', max_length=250, verbose_name='votre nom')),
                ('adresse', models.CharField(max_length=250, verbose_name='Votre adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Votre ville')),
                ('nbsal', models.PositiveIntegerField(verbose_name='Nombre de salariés')),
                ('freq', models.IntegerField(choices=[(5, 'moins de 1 jour'), (15, '1 jour'), (35, '2 jours'), (65, '3 jours'), (80, '4 jours'), (100, '5 jours')], default=65, verbose_name="fréquence d'utilisation")),
                ('dist', models.IntegerField(default=3, verbose_name='Distance Domicile travail moyenne des cyclistes de votre entreprise')),
                ('access', models.CharField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], default='Bonne', max_length=10, verbose_name='Accessibilite du site')),
                ('ctxgeolib', models.FloatField(choices=[(4.9, 'Centre ville ou urbain'), (1.7, 'Périurbain'), (1.5, 'Rural'), (2.2, 'Moyenne nationale')], default='Centre-ville', verbose_name='Contexte geographique')),
                ('g1', models.IntegerField(choices=[(10, 'Réticent'), (25, 'Non sensibilisé'), (45, 'Sensibilisé'), (75, 'Motivé'), (100, 'Impliqué et acteur')], verbose_name='Motivation de la direction de l’entreprise')),
                ('g2', models.IntegerField(choices=[(10, 'Réfractaire aux vélos'), (25, 'Sensibilisé mais apeuré'), (45, 'Usager ponctuel pour le loisir'), (75, 'Usager quotidien'), (100, 'Cycliste expert')], verbose_name='Motivation des salariés')),
                ('g3', models.IntegerField(choices=[(10, 'Pas acté'), (50, 'Démarche en cours'), (100, 'Démarche lancée')], verbose_name="Etat d'avancement du PDE")),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
