# Generated by Django 2.0.5 on 2018-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='PM',
            field=models.IntegerField(default=0, verbose_name='Part Modale vélo Attendue (Pour débugages)'),
        ),
    ]
