# Generated by Django 2.0.1 on 2018-04-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='published_date',
        ),
    ]
