# Generated by Django 2.0.4 on 2018-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='g4',
            field=models.IntegerField(choices=[(10, 'Aucune action envisagée'), (50, 'Actions  vélos en réflexion'), (100, 'Actions vélos mises en place')], default=50, verbose_name='Actions vélo'),
        ),
    ]
