# Generated by Django 2.0.4 on 2018-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0002_player_g4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='g1',
            field=models.IntegerField(choices=[(2, 'Réticent'), (25, 'Non sensibilisé'), (45, 'Sensibilisé'), (75, 'Motivé'), (100, 'Impliqué et acteur')], verbose_name='Motivation de la direction de l’entreprise'),
        ),
        migrations.AlterField(
            model_name='player',
            name='g2',
            field=models.IntegerField(choices=[(10, 'Réfractaire aux vélos'), (25, 'Sensibilisé mais pas confiant'), (45, 'Usager ponctuel pour le loisir'), (75, 'Usager quotidien'), (100, 'Cycliste expert')], verbose_name='Motivation des salariés'),
        ),
        migrations.AlterField(
            model_name='player',
            name='g4',
            field=models.IntegerField(choices=[(10, 'Aucune action envisagée'), (50, 'Actions vélos en réflexion'), (100, 'Actions vélos mises en place')], default=50, verbose_name='Actions vélo'),
        ),
    ]
