# Generated by Django 2.0.5 on 2018-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0002_player_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mail',
            field=models.EmailField(default='votre@mail.com', max_length=254, verbose_name='Votre email'),
        ),
    ]
