# Generated by Django 2.0.1 on 2018-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0002_auto_20180408_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nom',
        ),
    ]
