# Generated by Django 2.0.5 on 2018-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0003_auto_20180619_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pccycliste',
            field=models.PositiveIntegerField(default='3', verbose_name='NPourcentages cyclistes'),
        ),
    ]
