# Generated by Django 2.0.5 on 2018-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0003_player_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='entrep',
            field=models.CharField(max_length=250, verbose_name='Le nom de votre entreprise'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Votre email'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='votre nom'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ville',
            field=models.CharField(max_length=250, verbose_name='Votre ville'),
        ),
    ]
