# Generated by Django 2.0.1 on 2018-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0004_player_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dist',
            field=models.IntegerField(default=3, verbose_name='Distance Domicile travail moyenne des cyclistes de votre entreprise'),
        ),
        migrations.AddField(
            model_name='player',
            name='freq',
            field=models.FloatField(default=65, verbose_name='Fréquence moyenne de la pratique des cycliste (en pourcentages de jours travaillés)'),
        ),
    ]
