# Generated by Django 2.0.5 on 2018-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0004_auto_20181128_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ctxgeolib',
            field=models.FloatField(choices=[(4.9, 'Centre ville ou urbain'), (1.7, 'Périurbain'), (1.5, 'Rural')], default='Centre-ville', verbose_name='Contexte geographique'),
        ),
    ]
