# Generated by Django 2.0.1 on 2018-04-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0005_auto_20180416_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='partmodal',
        ),
        migrations.RemoveField(
            model_name='player',
            name='txpratique',
        ),
    ]
