# Generated by Django 2.1.2 on 2019-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0005_auto_20181128_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='access',
            field=models.CharField(choices=[('bonne', 'Bonne'), ('moyenne', 'Moyenne'), ('mauvaise', 'Mauvaise')], default='Bonne', max_length=10, verbose_name='Accessibilite du site'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ctxgeolib',
            field=models.FloatField(choices=[(4.9, 'Centre ville ou urbain'), (1.7, "Périurbain ou zone d'activités"), (1.5, 'Rural')], default='Centre-ville', verbose_name='Contexte geographique'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pccycliste',
            field=models.PositiveIntegerField(choices=[(3, 'moins de 3%'), (5, 'entre 3 et 5%'), (8, 'entre 5 et 8%'), (55, 'Environ la moitié'), (80, 'Plus de la moitié'), (50, 'Ne sais pas estimer')], default='50', verbose_name='NPourcentages cyclistes'),
        ),
    ]
