# Generated by Django 2.1.2 on 2019-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0006_auto_20190228_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='PM',
        ),
        migrations.AlterField(
            model_name='player',
            name='g1',
            field=models.IntegerField(choices=[(2, 'Réticents'), (25, 'Non sensibilisés'), (45, 'Sensibilisés'), (75, 'Motivés'), (100, 'Impliqués et acteurs')], verbose_name='Motivation de la direction de l’entreprise'),
        ),
        migrations.AlterField(
            model_name='player',
            name='g2',
            field=models.IntegerField(choices=[(10, 'Réfractaires aux vélos'), (25, 'Sensibilisés mais pas confiants'), (45, 'Usagers ponctuels pour le loisir'), (75, 'Usagers au quotidien'), (100, 'Cyclistes experts')], verbose_name='Motivation des salariés'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pccycliste',
            field=models.PositiveIntegerField(choices=[(3, 'Moins de 3%'), (5, 'Entre 3 et 5%'), (8, 'Entre 5 et 8%'), (55, 'Environ la moitié'), (80, 'Plus de la moitié'), (50, 'Ne sais pas estimer')], default='50', verbose_name='NPourcentages cyclistes'),
        ),
    ]
