# Generated by Django 2.0.1 on 2018-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0006_auto_20180416_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='freq',
            field=models.IntegerField(default=0.65, verbose_name='Fréquence moyenne de la pratique des cycliste (en pourcentages de jours travaillés)'),
        ),
    ]
