# Generated by Django 2.0.5 on 2018-07-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0006_auto_20180703_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pccyclichk',
        ),
    ]
