# Generated by Django 2.0.1 on 2018-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0008_player_vctx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='freq',
            field=models.FloatField(default=0.65, verbose_name='Fréquence moyenne de la pratique des cycliste (en pourcentages de jours travaillés)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vctx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Var ctx'),
        ),
    ]
