# Generated by Django 2.0.5 on 2018-07-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0009_auto_20180704_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='freq',
        ),
    ]
