# Generated by Django 2.0.1 on 2018-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0009_auto_20180416_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nom',
            field=models.CharField(default='votre nom', max_length=250, verbose_name='votre nom'),
        ),
    ]
