# Generated by Django 2.0.5 on 2018-07-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0010_remove_player_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pccycliste',
            field=models.PositiveIntegerField(choices=[(3, 'Moins de 5 %'), (20, 'Environ un quart'), (55, 'Environ la moitié'), (80, 'Plus de la moitié'), (50, 'Ne sais pas estimer')], default='50', verbose_name='NPourcentages cyclistes'),
        ),
    ]
