# Generated by Django 2.1.2 on 2018-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.RemoveField(
            model_name='choixaction',
            name='NumFiche',
        ),
        migrations.AddField(
            model_name='choixaction',
            name='entrep',
            field=models.CharField(default='', max_length=250, verbose_name='Le nom de votre entreprise'),
        ),
        migrations.AddField(
            model_name='choixaction',
            name='lstfiche',
            field=models.CharField(default='', max_length=400, verbose_name='Selectionnez les fiches désirées'),
        ),
    ]
