# Generated by Django 2.1.2 on 2018-12-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20181215_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choixaction',
            name='lstfiche',
        ),
    ]
