# Generated by Django 2.1.2 on 2018-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_remove_choixaction_lstfiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='choixaction',
            name='lstaction',
            field=models.CharField(default='', max_length=400, verbose_name='code des actions selectionnees dans une liste python'),
        ),
    ]
