# Generated by Django 2.1.2 on 2018-12-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_remove_choixaction_lstaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoixAction',
            new_name='Site',
        ),
    ]
