# Generated by Django 2.1.2 on 2018-12-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20181215_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='entrep',
            new_name='nom',
        ),
    ]
