# Generated by Django 2.1.2 on 2018-12-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_site_lstaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
