# Generated by Django 2.1.2 on 2018-12-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_site'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='actiondb',
        ),
    ]
