# Generated by Django 2.1.2 on 2018-12-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_auto_20181218_2134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table=None,
        ),
    ]
