# Generated by Django 2.1.2 on 2018-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0015_auto_20181218_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='enjeux',
            field=models.CharField(default='', max_length=250, verbose_name="enjeux de l'action"),
        ),
    ]
