# Generated by Django 2.1.2 on 2018-12-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_auto_20181218_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='actionprio',
            field=models.CharField(default='', max_length=250, verbose_name='Première actions à engager'),
        ),
        migrations.AddField(
            model_name='action',
            name='cible',
            field=models.CharField(default='', max_length=250, verbose_name='Cible'),
        ),
        migrations.AddField(
            model_name='action',
            name='constat',
            field=models.CharField(default='', max_length=250, verbose_name='Constat'),
        ),
        migrations.AddField(
            model_name='action',
            name='consultant',
            field=models.CharField(default='', max_length=250, verbose_name='Nom du consultant'),
        ),
        migrations.AddField(
            model_name='action',
            name='couleur',
            field=models.CharField(default='', max_length=250, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='action',
            name='cout_fonct',
            field=models.CharField(default='', max_length=250, verbose_name='Coûts de fonctionnement'),
        ),
        migrations.AddField(
            model_name='action',
            name='cout_invest',
            field=models.CharField(default='', max_length=250, verbose_name="Coût d'investissement"),
        ),
        migrations.AddField(
            model_name='action',
            name='datepdm',
            field=models.CharField(default='', max_length=250, verbose_name='Date du Plan de mobilité'),
        ),
        migrations.AddField(
            model_name='action',
            name='impacts',
            field=models.CharField(default='', max_length=250, verbose_name='Impacts'),
        ),
        migrations.AddField(
            model_name='action',
            name='indicateurs',
            field=models.CharField(default='', max_length=250, verbose_name='Indicateurs'),
        ),
        migrations.AddField(
            model_name='action',
            name='numfiche',
            field=models.CharField(default='', max_length=250, verbose_name='Numéro de fiche'),
        ),
        migrations.AddField(
            model_name='action',
            name='objectif',
            field=models.CharField(default='', max_length=250, verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='action',
            name='partenaires',
            field=models.CharField(default='', max_length=250, verbose_name='Partenaires'),
        ),
        migrations.AddField(
            model_name='action',
            name='periodicite',
            field=models.CharField(default='', max_length=250, verbose_name='Périodicité de relevé des indicateurs'),
        ),
        migrations.AddField(
            model_name='action',
            name='planning',
            field=models.CharField(default='', max_length=250, verbose_name='Planning'),
        ),
        migrations.AddField(
            model_name='action',
            name='plusloin',
            field=models.CharField(default='', max_length=250, verbose_name='Pour aller plus loin'),
        ),
        migrations.AddField(
            model_name='action',
            name='porteurs',
            field=models.CharField(default='', max_length=250, verbose_name="Porteur de l'action"),
        ),
        migrations.AddField(
            model_name='action',
            name='priorite',
            field=models.CharField(default='', max_length=250, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='action',
            name='réussite',
            field=models.CharField(default='', max_length=250, verbose_name='Facteurs de réussite'),
        ),
        migrations.AddField(
            model_name='action',
            name='typeaction',
            field=models.CharField(default='', max_length=250, verbose_name="Typologie d'action"),
        ),
        migrations.AlterField(
            model_name='action',
            name='enjeux',
            field=models.CharField(default='', max_length=250, verbose_name='Enjeux'),
        ),
        migrations.AlterField(
            model_name='action',
            name='nomfiche',
            field=models.CharField(default='', max_length=250, verbose_name='Nom de fiche'),
        ),
    ]
