# Generated by Django 2.1.2 on 2018-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0017_auto_20181218_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='cible',
            new_name='ccible',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='réussite',
            new_name='factreu',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='porteurs',
            new_name='porteur',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='plusloin',
            new_name='tellmemore',
        ),
        migrations.RemoveField(
            model_name='action',
            name='actionprio',
        ),
        migrations.RemoveField(
            model_name='action',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='action',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='action',
            name='cout_fonct',
        ),
        migrations.RemoveField(
            model_name='action',
            name='cout_invest',
        ),
        migrations.RemoveField(
            model_name='action',
            name='datepdm',
        ),
        migrations.RemoveField(
            model_name='action',
            name='enjeux',
        ),
        migrations.RemoveField(
            model_name='action',
            name='partenaires',
        ),
        migrations.RemoveField(
            model_name='action',
            name='priorite',
        ),
        migrations.AddField(
            model_name='action',
            name='catenjeux',
            field=models.CharField(default='', max_length=250, verbose_name="Catégorie d'enjeux"),
        ),
        migrations.AddField(
            model_name='action',
            name='cfonctionchi',
            field=models.CharField(default='', max_length=250, verbose_name='Coût de fonctionnement chiffré'),
        ),
        migrations.AddField(
            model_name='action',
            name='cfonctiondet',
            field=models.CharField(default='', max_length=250, verbose_name='Coûts de fonctionnement détail'),
        ),
        migrations.AddField(
            model_name='action',
            name='cinvestchi',
            field=models.CharField(default='', max_length=250, verbose_name="Coût d'investissement chiffré"),
        ),
        migrations.AddField(
            model_name='action',
            name='cinvestdet',
            field=models.CharField(default='', max_length=250, verbose_name="Coût d'investissement détail"),
        ),
        migrations.AddField(
            model_name='action',
            name='codecouleur',
            field=models.CharField(default='', max_length=250, verbose_name='Code couleur'),
        ),
        migrations.AddField(
            model_name='action',
            name='indicateurs_tp',
            field=models.CharField(default='', max_length=250, verbose_name='Périodicité de relevé des indicateurs'),
        ),
        migrations.AddField(
            model_name='action',
            name='intervenant',
            field=models.CharField(default='', max_length=250, verbose_name='Intervenants potentiels'),
        ),
        migrations.AddField(
            model_name='action',
            name='objmoyen',
            field=models.CharField(default='', max_length=250, verbose_name="Moyens pour atteindre l'objectif"),
        ),
        migrations.AlterField(
            model_name='action',
            name='impacts',
            field=models.CharField(default='', max_length=250, verbose_name='Impacts: facilité de mise en œuvre, innovation et image du territoire, économie de CO2 réalisée, amélioration du climat social,\xa0 moyens financiers et humains à mettre en œuvre'),
        ),
        migrations.AlterField(
            model_name='action',
            name='periodicite',
            field=models.CharField(default='', max_length=250, verbose_name='Priorité '),
        ),
    ]
